export enum ReviewStatus {
    SUBMITTED,
    CONTENT_MANAGER_ACCEPTED,
    CONTENT_MANAGER_REJECTED,
    CM_ADMIN_ACCEPTED,
    REVIEWER_ACCEPTED,
    REVIEWER_REJECTED,
    REVIEWER_RESUBMIT,
    ADMIN_ACCEPTED,
    ADMIN_RESUBMIT,
    ADMIN_REJECTED
}